export const LOGIN_ACTION_TYPES = {
    TRY_LOGIN: 'TRY_LOGIN',
    SET_ERROR: 'SET_ERROR'
};
export const SHIP_GET_DATA = {
    GET_DATA: 'GET_DATA',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_ERROR: 'GET_DATA_ERROR'

};