export const LOGIN_ACTION_TYPES = {
    TRY_LOGIN: 'TRY_LOGIN',
    SET_ERROR: 'SET_ERROR'
};
export const VESSEL_ACTION_TYPES = {
    GET_DATA: 'GET_DATA',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_ERROR: 'GET_DATA_ERROR'

};

export const SHIP_DETAILS_MAP = {
    TOGGLE_FOOTER: 'SHIP_DETAILS_MAP'
};

